FROM apache/airflow:2.10.0

USER airflow

RUN pip install --no-cache-dir \
    psycopg2-binary \
    pandas \
    sqlalchemy \
    faker \
    spotipy \
    boto3 \
    duckdb \
    pyarrow \
    python-dotenv \
    requests